# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-09 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_pic',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
